package typings
package atPulumiAwsLib.cloudfrontPublicKeyMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait PublicKeyArgs extends js.Object {
  /**
    * An optional comment about the public key.
    */
  val comment: js.UndefOr[atPulumiPulumiLib.resourceMod.Input[java.lang.String]] = js.undefined
  /**
    * The encoded public key that you want to add to CloudFront to use with features like field-level encryption.
    */
  val encodedKey: atPulumiPulumiLib.resourceMod.Input[java.lang.String]
  /**
    * The name for the public key. By default generated by Terraform.
    */
  val name: js.UndefOr[atPulumiPulumiLib.resourceMod.Input[java.lang.String]] = js.undefined
  /**
    * The name for the public key. Conflicts with `name`.
    */
  val namePrefix: js.UndefOr[atPulumiPulumiLib.resourceMod.Input[java.lang.String]] = js.undefined
}

object PublicKeyArgs {
  @scala.inline
  def apply(
    encodedKey: atPulumiPulumiLib.resourceMod.Input[java.lang.String],
    comment: atPulumiPulumiLib.resourceMod.Input[java.lang.String] = null,
    name: atPulumiPulumiLib.resourceMod.Input[java.lang.String] = null,
    namePrefix: atPulumiPulumiLib.resourceMod.Input[java.lang.String] = null
  ): PublicKeyArgs = {
    val __obj = js.Dynamic.literal(encodedKey = encodedKey.asInstanceOf[js.Any])
    if (comment != null) __obj.updateDynamic("comment")(comment.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name.asInstanceOf[js.Any])
    if (namePrefix != null) __obj.updateDynamic("namePrefix")(namePrefix.asInstanceOf[js.Any])
    __obj.asInstanceOf[PublicKeyArgs]
  }
}

