package typings
package arcgisDashJsDashApiLib.underscoreUnderscoreEsriNs

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait CredentialProperties extends js.Object {
  /**
    * Token expiration time specified as number of milliseconds since 1 January 1970 00:00:00 UTC.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#expires)
    */
  var expires: js.UndefOr[scala.Double] = js.undefined
  /**
    * Indicates that this credential was created to access the [ArcGIS REST Admin service](https://developers.arcgis.com/rest/services-reference/rest-api-admin.htm).
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#isAdmin)
    */
  var isAdmin: js.UndefOr[scala.Boolean] = js.undefined
  /**
    * The Identity Manager's [setOAuthRedirectionHandler](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#setOAuthRedirectionHandler) returns an object that contains a `state` property. This information is returned for this property.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#oAuthState)
    */
  var oAuthState: js.UndefOr[js.Any] = js.undefined
  /**
    * The server url.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#server)
    */
  var server: js.UndefOr[java.lang.String] = js.undefined
  /**
    * Indicates whether the resources accessed using this credential should be fetched over HTTPS protocol.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#ssl)
    */
  var ssl: js.UndefOr[scala.Boolean] = js.undefined
  /**
    * Token generated by the token service using the specified userId and password.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#token)
    */
  var token: js.UndefOr[java.lang.String] = js.undefined
  /**
    * User associated with the Credential object.
    *
    * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html#userId)
    */
  var userId: js.UndefOr[java.lang.String] = js.undefined
}

